import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export const getServerSideProps = async (ctx) => {
  console.log(ctx);
  return {
    props: {},
  };
};
export default function Home() {
  const navMenu = ["Home", "Story", "NFT", "Roadmap", "About us"];
  return (
    <div className="flex h-screen flex-col border-4_ border-red-300 ">
      <Head>
        <title>DeBalance NFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-1 bg-[#EFF5F5]">
        <div className="flex-1 border-4_ overflow-hidden overflow-y-auto_ h-[100vh] scroll-smooth border-green-500">
          <div className="sections-container flex flex-1 flex-col border-4_ border-orange-500 gap-4">
            <section
              id="Home"
              className="h-screen border-4_ border-blue-500 grid place-items-center"
            >
              Home
            </section>
            <section
              id="Story"
              className="h-screen border-4_ border-blue-500 grid place-items-center isolate"
            >
              <div className="home-content-container max-w-[1500px] flex">
                <section className="basis-1/2 grow pl-4">
                  <h1 className="text-6xl text-[#EB6440] font-[PBCaps]">DeBalance NFT</h1>
                  <p className="text-lg text-[#497174] font-[VarelaR]">
                    DeBalance NFT adalah koleksi NFT serial yang berjalan diatas
                    jaringan blockchain Algorand. Proyek merupakan bagian dari
                    mega proyek MANDALIKA SERIES, sebuah proyek yang di inisiasi
                    oleh komunitas KawanCrypto, Lombok Blockchain Society,
                    Kawanduit, Enjoy Life Foundation dan Komunitas Pendidikan di
                    Lombok. Dalam proyek ini kami merilis 7500 karakter yang
                    dirilis sesuai volume berseri yang diwakili oleh karakter
                    yang berbeda beda. Setiap karakter diwakili oleh corak,
                    warna, desain dan tema yang berbeda sehingga masing masing
                    memiliki keunikan yang identic dengan kebudayan dan nilai
                    nilai yang berkembang di Lombok. Untuk menambah unsur FUN
                    pada proyek ini kami menyelipkan beberapa karakter yang
                    benar benar terbatas (limited edition).{" "}
                  </p>
                </section>
                <section className="relative basis-1/3 z-[-1]">
                  <div className="nft-img-container overflow-hidden w-96 rounded-full absolute -top-60 -left-20">
                    <Image
                      src="/Images/NFTs/93.png"
                      alt="Picture of the author"
                      width={1000} 
                      height={1000} 
                      // blurDataURL="data:..." automatically provided
                      // placeholder="blur" // Optional blur-up while loading
                    />
                  </div>
                  <div className="nft-img-container overflow-hidden w-72 rounded-full absolute top-0 -right-20">
                    <Image
                      src="/Images/NFTs/442.png"
                      alt="Picture of the author"
                      width={1000} 
                      height={1000} 
                      // blurDataURL="data:..." automatically provided
                      // placeholder="blur" // Optional blur-up while loading
                    />
                  </div>
                  <div className="nft-img-container overflow-hidden w-52 rounded-full absolute top-40 left-20">
                    <Image
                      src="/Images/NFTs/497.png"
                      alt="Picture of the author"
                      width={1000} 
                      height={1000} 
                      // blurDataURL="data:..." automatically provided
                      // placeholder="blur" // Optional blur-up while loading
                    />
                  </div>
                </section>
              </div>
            </section>
          </div>
        </div>
        <aside className="border-4_ flex justify-center items-center p-4">
          <div className="nav-container flex flex-col gap-2">
            {navMenu.map((d, i) => (
              <a href={`#${d}`} key={i} className="relative group">
                <nav className="p-2 pb-0 pr-0 text-[#497174] border-b-2 border-[#D6E4E5] text-right font-[PBCaps] hover:text-[#EB6440] transition-all">
                  {d}
                </nav>
                
                <span className="absolute flex group-hover:bg-[#EB6440] w-0 bottom-0 right-0 p-[1px] group-hover:w-full transition-all ease-out duration-500"></span>
              </a>
            ))}
          </div>
        </aside>
      </main>
      {/* <footer className="">just a footer</footer> */}
    </div>
  );
}
